on:
  push:
    branches: [master]

jobs:
  build:
    name: 🐘 Desplegar
    runs-on: ubuntu-latest

    steps:
      - name: 🐯 Obtener código del repositorio
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USUARIO }}
          key: ${{ secrets.SSH_SECRET }}
          port: 22
          script: |
            cd apps/enflujo-www/
            git pull origin master
            git status
